# Generated by Django 4.2.27 on 2025-12-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_ru", models.CharField(max_length=200, null=True)),
                ("title_uz", models.CharField(max_length=200, null=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField()),
                ("description_en", models.TextField(null=True)),
                ("description_ru", models.TextField(null=True)),
                ("description_uz", models.TextField(null=True)),
                ("short_description", models.CharField(blank=True, max_length=300)),
                (
                    "short_description_en",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "short_description_ru",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "short_description_uz",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("location", models.CharField(max_length=200)),
                ("location_en", models.CharField(max_length=200, null=True)),
                ("location_ru", models.CharField(max_length=200, null=True)),
                ("location_uz", models.CharField(max_length=200, null=True)),
                ("event_date", models.DateField()),
                ("event_time", models.TimeField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="events/"),
                ),
                ("registration_link", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["event_date", "event_time"],
            },
        ),
    ]
