# Generated by Django 4.2.27 on 2025-12-20 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100, null=True)),
                ("name_ru", models.CharField(max_length=100, null=True)),
                ("name_uz", models.CharField(max_length=100, null=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#84cc16", help_text="Hex color code", max_length=20
                    ),
                ),
            ],
            options={
                "verbose_name": "News Category",
                "verbose_name_plural": "News Categories",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_ru", models.CharField(max_length=200, null=True)),
                ("title_uz", models.CharField(max_length=200, null=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("excerpt", models.TextField(blank=True, max_length=300)),
                ("excerpt_en", models.TextField(blank=True, max_length=300, null=True)),
                ("excerpt_ru", models.TextField(blank=True, max_length=300, null=True)),
                ("excerpt_uz", models.TextField(blank=True, max_length=300, null=True)),
                ("content", models.TextField()),
                ("content_en", models.TextField(null=True)),
                ("content_ru", models.TextField(null=True)),
                ("content_uz", models.TextField(null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="news/")),
                ("author", models.CharField(blank=True, max_length=100)),
                ("is_published", models.BooleanField(default=True)),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news",
                        to="news.newscategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "News Article",
                "verbose_name_plural": "News Articles",
                "ordering": ["-published_date"],
            },
        ),
    ]
