# Generated by Django 4.2.27 on 2025-12-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=200)),
                ("position_en", models.CharField(max_length=200, null=True)),
                ("position_ru", models.CharField(max_length=200, null=True)),
                ("position_uz", models.CharField(max_length=200, null=True)),
                ("bio", models.TextField(blank=True)),
                ("bio_en", models.TextField(blank=True, null=True)),
                ("bio_ru", models.TextField(blank=True, null=True)),
                ("bio_uz", models.TextField(blank=True, null=True)),
                ("short_bio", models.CharField(blank=True, max_length=300)),
                (
                    "short_bio_en",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "short_bio_ru",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "short_bio_uz",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="team/")),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("joined_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["order", "name"],
            },
        ),
    ]
