# Generated by Django 4.2.27 on 2025-12-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Full Name")),
                (
                    "role",
                    models.CharField(max_length=200, verbose_name="Role/Position"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="LinkedIn Profile",
                    ),
                ),
                (
                    "twitter",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Twitter Profile",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="team/", verbose_name="Profile Image"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["order", "name"],
            },
        ),
    ]
