# Generated by Django 4.2.27 on 2025-12-25
# Migration to add modeltranslation fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teammember_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Role/Position'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Role/Position'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Role/Position'),
        ),
    ]
