# Generated by Django 4.2.27 on 2025-12-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_ru", models.CharField(max_length=200, null=True)),
                ("title_uz", models.CharField(max_length=200, null=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField()),
                ("description_en", models.TextField(null=True)),
                ("description_ru", models.TextField(null=True)),
                ("description_uz", models.TextField(null=True)),
                ("short_description", models.CharField(blank=True, max_length=300)),
                (
                    "short_description_en",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "short_description_ru",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "short_description_uz",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🌱", help_text="Emoji or icon class", max_length=50
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="programs/"),
                ),
                (
                    "impact_stat",
                    models.CharField(
                        blank=True,
                        help_text='e.g., "2.3M Trees Planted"',
                        max_length=100,
                    ),
                ),
                (
                    "impact_stat_en",
                    models.CharField(
                        blank=True,
                        help_text='e.g., "2.3M Trees Planted"',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "impact_stat_ru",
                    models.CharField(
                        blank=True,
                        help_text='e.g., "2.3M Trees Planted"',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "impact_stat_uz",
                    models.CharField(
                        blank=True,
                        help_text='e.g., "2.3M Trees Planted"',
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Program",
                "verbose_name_plural": "Programs",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
